### PR TITLE
Option to add Subtitle for each date as a label in the view

### PR DESCRIPTION
**Pull request by skymansandy**
Hi 

[Closed the previous PR & created New PR for convenience]

We've communicated before regarding the "**unavailable dates**" marking issue and I was unable to do it, I changed my implementation of `equals()` to match that of your examples and it worked. First of all cheers for that.

I actually liked your library very much and while playing with it, I came up with this idea of adding subtitle for each date and wrote down the code for it, We can see the effect in "_Example 2_" of your examples. If it's worth merging, Could you accept my contribution for the library?

Thanks :)

### CODE REVIEW

**Comment by RafalManka** [comment]
Check out this pull request, I achieved the same by using spans: https://github.com/RafalManka/ScrollCalendar/pull/21/files

**Comment by skymansandy** [comment]
Nice approach with less steps. Cool :)

**Comment by RafalManka** [comment]
Grea, let's close this pull request and switch to the other one. When it comes to the interface I'm not sold. I'll try to make it using factory pattern

**Comment by skymansandy** [comment]
Cool cheers!

**Pull request closed without merging**
